//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaMind.AcutanceUnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaMind.AcutanceUnitTest.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Everyday - 8:0:0]
        ///
        ///    COMMAND: 1. You must trust yourself and must be able to stand up again. This is the tried and proved way to clean up negative emotion! 
        ///
        ///    MUSIC: 1. Stand Up Battle Formation Again!
        ///           2. Against The Pressure.
        /// </summary>
        internal static string AScheduleSample {
            get {
                return ResourceManager.GetString("AScheduleSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMAND: 1. You must trust yourself and must be able to stand up again. This is the tried and proved way to clean up negative emotion!.
        /// </summary>
        internal static string AScheduleSampleCommandContent {
            get {
                return ResourceManager.GetString("AScheduleSampleCommandContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMAND: 1. You must trust yourself and must be able to stand up again. This is the tried and proved way to clean up negative emotion! 
        ///
        ///    MUSIC: 1. Stand Up Battle Formation Again!
        ///           2. Against The Pressure.
        /// </summary>
        internal static string AScheduleSampleScheduleContent {
            get {
                return ResourceManager.GetString("AScheduleSampleScheduleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Everyday - 8:0:0]
        ///
        ///    COMMAND: 1. You must trust yourself and must be able to stand up again. This is the tried and proved way to clean up negative emotion! 
        ///
        ///    MUSIC: 1. Stand Up Battle Formation Again!
        ///           2. Against The Pressure
        ///
        ///[Everyday - 8:0:0]
        ///
        ///    COMMAND: 1. You must trust your friends that they will like you. If they leave you, you must be alone till yourself stand up again. People would come back someday..
        /// </summary>
        internal static string TwoScheduleSample {
            get {
                return ResourceManager.GetString("TwoScheduleSample", resourceCulture);
            }
        }
    }
}
