//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaMind.Acutance.PerseveranceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerseveranceServiceReference.ISynchronizationService")]
    public interface ISynchronizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/Fetch", ReplyAction="http://tempuri.org/ISynchronizationService/FetchResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Perseverance.Concepts.Cognitions.Synchronization))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Perseverance.Concepts.Cognitions.SynchronizationDataProcessor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Perseverance.Concepts.Cognitions.SynchronizationDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Perseverance.Concepts.Cognitions.SynchronizationDailyStatistics))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Perseverance.Concepts.Cognitions.SynchronizationTimer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Engine.EngineObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetaMind.Engine.Concepts.Experience))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(double[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.TimeSpan[]))]
        object Fetch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/Fetch", ReplyAction="http://tempuri.org/ISynchronizationService/FetchResponse")]
        System.Threading.Tasks.Task<object> FetchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/FetchTask", ReplyAction="http://tempuri.org/ISynchronizationService/FetchTaskResponse")]
        MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry FetchTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/FetchTask", ReplyAction="http://tempuri.org/ISynchronizationService/FetchTaskResponse")]
        System.Threading.Tasks.Task<MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry> FetchTaskAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISynchronizationServiceChannel : MetaMind.Acutance.PerseveranceServiceReference.ISynchronizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynchronizationServiceClient : System.ServiceModel.ClientBase<MetaMind.Acutance.PerseveranceServiceReference.ISynchronizationService>, MetaMind.Acutance.PerseveranceServiceReference.ISynchronizationService {
        
        public SynchronizationServiceClient() {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Fetch() {
            return base.Channel.Fetch();
        }
        
        public System.Threading.Tasks.Task<object> FetchAsync() {
            return base.Channel.FetchAsync();
        }
        
        public MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry FetchTask() {
            return base.Channel.FetchTask();
        }
        
        public System.Threading.Tasks.Task<MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry> FetchTaskAsync() {
            return base.Channel.FetchTaskAsync();
        }
    }
}
