//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaMind.Acutance.PerseveranceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerseveranceServiceReference.ISynchronizationService")]
    public interface ISynchronizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/GetSynchronizedTask", ReplyAction="http://tempuri.org/ISynchronizationService/GetSynchronizedTaskResponse")]
        MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry GetSynchronizedTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronizationService/GetSynchronizedTask", ReplyAction="http://tempuri.org/ISynchronizationService/GetSynchronizedTaskResponse")]
        System.Threading.Tasks.Task<MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry> GetSynchronizedTaskAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISynchronizationServiceChannel : MetaMind.Acutance.PerseveranceServiceReference.ISynchronizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynchronizationServiceClient : System.ServiceModel.ClientBase<MetaMind.Acutance.PerseveranceServiceReference.ISynchronizationService>, MetaMind.Acutance.PerseveranceServiceReference.ISynchronizationService {
        
        public SynchronizationServiceClient() {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry GetSynchronizedTask() {
            return base.Channel.GetSynchronizedTask();
        }
        
        public System.Threading.Tasks.Task<MetaMind.Perseverance.Concepts.TaskEntries.TaskEntry> GetSynchronizedTaskAsync() {
            return base.Channel.GetSynchronizedTaskAsync();
        }
    }
}
